### ISSUE TITLE
Could you create a nuget package for this?

### ISSUE THREAD

**Issue by georgiosd** [basarat/typescript-collections#1]
Excellent effort! Could you please create a NuGet package for it?

Thanks

**Comment by basarat** [comment]
I'll try to. But have a busy schedule with new job, and conference speaking engagements coming up.

**Comment by basarat** [comment]
Thanks for the lovely comment :)

**Comment by georgiosd** [comment]
I'll send you a pull request, I made one for bootstrap-sass :)

**Comment by basarat** [comment]
That would be highly appreciated!
