### ISSUE TITLE
Default compare broken

### ISSUE THREAD

**Issue by sirian** [basarat/typescript-collections#104]
Current version defaultCompare is wrong IMO

https://github.com/basarat/typescript-collections/blob/6c14e8f21cb378dd29f03358db62d48cd7395550/src/lib/util.ts#L34
```
export function defaultCompare<T>(a: T, b: T): number {
    if (a < b) {
        return -1;
    } else if (a === b) {
        return 0;
    } else {
        return 1;
    }
}
```

![image](https://user-images.githubusercontent.com/897643/55077070-f4e63980-50a7-11e9-8fa6-71f828172759.png)

upd:

![image](https://user-images.githubusercontent.com/897643/55082473-cae64480-50b2-11e9-82ec-577134e5410f.png)

**Comment by sirian** [comment]
Look semantic of default sort compare and abstract relational comparison
http://www.ecma-international.org/ecma-262/8.0/#sec-sortcompare
http://www.ecma-international.org/ecma-262/8.0/#sec-abstract-relational-comparison

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.

**Comment by sirian** [comment]
Issue still persist - actual defaultCompare https://github.com/basarat/typescript-collections/blob/release/src/lib/util.ts#L34 is same as https://github.com/basarat/typescript-collections/issues/104#issue-425941639
