### ISSUE TITLE
trying to include as a dependency from github repo through npm results in empty dependency 

### ISSUE THREAD

**Issue by aino-debasish** [basarat/typescript-collections#105]
I am trying to add content of this repo through a well known npm mechanism by adding this line to my package.json as below -

"typescript-collections": "https://github.com/basarat/typescript-collections/tarball/release"

but it results in an empty folder in the node_modules after I run npm install. 

any clues as to how to include this  directly from the repo as a npm dependency ?

**Comment by aino-debasish** [comment]
solution - directly use the package from npm repository version 1.3.2 .. 

and then refer to this to import 

https://stackoverflow.com/questions/42791897/typescript-error-cannot-find-module-typescript-collections-when-changing-the-m/55675162#55675162

**Comment by episage** [comment]
If the issue persists, discuss it here and/or open a Pull Request please.

Thanks for the workaround!
