### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Veetaha** [basarat/typescript-collections#106]
This package seems to be popular and worth maintaining, but there have been no feedback from the developers on the issues and PRs for almost a year.

Could you please answer whether you are going to maintain this repo or add active users who are willing to keep this project alive. If you have no time to keep it running, you might add me to the collaborators and I'll do what I can to save it.

**Comment by aino-debasish** [comment]
@Veetaha doesn't seem so but the dependency on npm registry seems to do the job 

- https://www.npmjs.com/package/typescript-collections

**Comment by aino-debasish** [comment]
I tried using the dep from npm registry but to no avail. It throws out a weird set of errors that prevent the package from being used. Finally I ended up simply copying the code sans test cases, examples and other code directly into my repo

**Comment by Veetaha** [comment]
> @Veetaha doesn't seem so but the dependency on npm registry seems to do the job

@aino-gautam What do you mean by `do the job`. This package was last time updated a year ago, there is no feedback from the developers.



> I tried using the dep from npm registry but to no avail. It throws out a weird set of errors that prevent the package from being used. Finally, I ended up simply copying the code sans test cases, examples and other code directly into my repo

Sorry if I got you wrong, but this package throws no errors in production (when using it with npm as a dependency). Do you maintain this repo? Otherwise, there is no big sense in forking it as nobody can accept your pull requests.

**Comment by aino-debasish** [comment]
the package code is fully usable and I am able to use it after copying the code directly into my project. 

As for the npm dependency, the structure of the npm module is not accepted by typescript compiler and throws a set of errors for es2015 module target.

**Comment by episage** [comment]
Hi everyone. I can accept PRs. Please make sure that they pass tests and don't break existing code.
