### ISSUE TITLE
vanilla Typescript app with Webpack

### ISSUE THREAD

**Issue by SergeyOrlovIE** [basarat/typescript-collections#110]
Module not found: Error: Can't resolve 'typescript-collections/dist/lib/Dictionary' 
What I must to do?
tsc command build all ts files

**Comment by episage** [comment]
import `typescript-collections` instead of `typescript-collections/dist/lib/Dictionary`

**Comment by SergeyOrlovIE** [comment]
The same result. It was my first approach
