### ISSUE TITLE
The NuGet package includes unnecessary files.

### ISSUE THREAD

**Issue by MicahZoltu** [basarat/typescript-collections#15]
The NuGet package version 0.9.0 contains several files related to the building of the NuGet package but that should not be distributed.

Here is a list of the offenders:
- NuGet.exe
- build.ps1
- publish.ps1
- update.ps1

I believe this is because the nuspec file list is empty, so nuget is including every file/directory that is a sibling to the nuspec file.  You should be able to resolve this by adding this block to the nuspec file under the `package` element (untested, details found at http://docs.nuget.org/create/nuspec-reference#specifying-files-to-include-in-the-package):

``` xml
<files>
  <file src="content\*" target="content" />
</files>
```

**Comment by episage** [comment]
@basarat Can you bring NuGet repo up-to-date?

**Comment by episage** [comment]
@basarat or give me permissions/credentials

**Comment by basarat** [comment]
@episage need your username please : 

![image](https://cloud.githubusercontent.com/assets/874898/14301534/fdae3eec-fbdb-11e5-9c68-e8ae6ffa036c.png)

**Comment by episage** [comment]
@basarat Please try again with "episage".

**Comment by basarat** [comment]
@episage done :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/14314761/8f0062d4-fc3c-11e5-90c5-8119cc592b03.png)

**Comment by timecamp2** [comment]
Actually, @basarat, can you fix this issue please?
