### ISSUE TITLE
Compilation error under TS v1.0.3.0

### ISSUE THREAD

**Issue by ghost** [basarat/typescript-collections#16]
Hi!

I just have installed package and installed it for my project and have two errors in collection.ts file:

Type 'LinkedList<{}>' is not assignable to type 'LinkedList<T>'.  Type '{}' is not assignable to type 'T'. 
and 
Type '{}' is not assignable to type 'BSTreeNode<T>'.  Property 'element' is missing in type '{}'.

Apart that issues whole project is great :)

Thanks!
Aggie

**Comment by pasho** [comment]
Same problem when I enable "Redirect JavaScript output to directory" in the project TypeScript Build settings.

**Comment by basarat** [comment]
I just opened the repo right now, I see no errors. Can I have a screenshot?

**Comment by pasho** [comment]
Hi Basarat,

![errors](https://cloud.githubusercontent.com/assets/425689/7789543/e6b3b57e-025c-11e5-82f0-f7c383dd6cd5.png)

Got the package from nuget. It was easy to fix - just added some generic args in a couple of places.

**Comment by basarat** [comment]
Are those errors pointing it our file or other files in the project?

**Comment by pasho** [comment]
Yes, collections.ts. Is it the latest version in the nuget?

**Comment by basarat** [comment]
> Yes, collections.ts. Is it the latest version in the nuget?

Wasn't. Thanks. Pushed the latest :rose: : https://www.nuget.org/packages/typescript.collections/
