### ISSUE TITLE
Support Bower

### ISSUE THREAD

**Issue by cilerler** [basarat/typescript-collections#23]

**Comment by pkelleter** [comment]
+1
bower support would be much appreciated. in combination with tsd support to be able to provide a compiled js version of the library in combination with *.d.ts definitions

**Comment by basarat** [comment]
I'm sorry but bower will not be supported : https://medium.com/@basarat/friends-don-t-let-friends-use-bower-380bba84111a#.u3n72lm0f 

Lets all move to NPM. One less package manager you need to maintain / learn / keep up to date with :rose:
