### ISSUE TITLE
Split It Out Into Smaller Packages

### ISSUE THREAD

**Issue by mickdelaney** [basarat/typescript-collections#3]
Hi,
I was wondering if you considered splitting it out. If i only wanted to use X feature etc,
so that the overall size of the generated JS could be more fine grained.
Regards

**Comment by basarat** [comment]
+1 will look into it. Quite simple to do. But will need to document it and explain it which will be some work. 
Simple idea : a collections.ts looks like: 

//reference common.ts
//reference datatype1.ts
//reference datatype2.ts 

And collections.ts gets compiled to collections.js. And you can selectively delete lines from it and you can use only what you want.

**Comment by mickdelaney** [comment]
yeah, that'd be great. cheers

**Comment by episage** [comment]
Done it. Please check out version 1.1.0 . Download it via npm and look for ./dist/lib/*.(js/d.ts/js.map)
