### ISSUE TITLE
Cannot find name 'collections'

### ISSUE THREAD

**Issue by MickL** [basarat/typescript-collections#34]
This project looks awesome! Unfortionally i couldn't get it to work.

I placed it in a directory 'vendor' and referenced it like described:
`/// <reference path="vendor/typescript-collections/collections.ts" />`

Which gives me the error: Cannot find name 'collections'. Also i tried to compile the demo (demo/CollectionsDemo/app.ts) which gives me the same error.

**Comment by episage** [comment]
Please try again with version 1.1.0. Install it using npm and reference `node_modules/typescript-collections/dist/umd.min.js`

**Comment by episage** [comment]
Reopen if you still have the issue.
