### ISSUE TITLE
To/From JSON Support

### ISSUE THREAD

**Issue by jaynam15** [basarat/typescript-collections#44]
Hi
Please include to/from json support. 
JSON.stringigy(dictionary ); // this should print only a map and not meta data
dic = JSON.parse(str); //JSON should cast to Dictionary collection and you can identify the collection since it should have defined type.

**Comment by episage** [comment]
Hi @jaynam15 , thanks for using typescript-collections.

I'm afraid there's no nice way to make use of `JSON` as it is a standard built-in JS object. The only way to make this possible is to override it. But this is ugly.

As a workaround you can use `Collections.util.makeString` utility function to emulate `JSON.stringify` (section `makeString utility function` in README.md). 
There is no `JSON.parse` equivalent. You have to `JSON.parse` JSON and then insert them manually to an chosen collection. PRs are welcome

Best
episage
