### ISSUE TITLE
Compilation error on TS0.9.5.0

### ISSUE THREAD

**Issue by jensrodi** [basarat/typescript-collections#5]
I found to issues when compiling on TS0.9.5.0:

```
collections.ts(1511,13): error TS2012: Cannot convert 'LinkedList<{}>' to 'LinkedList<T>': Types of property 'firstNode' of types 'LinkedList<{}>' and 'LinkedList<T>' are incompatible: Types of property 'element' of types 'ILinkedListNode<{}>' and 'ILinkedListNode<T>' are incompatible.
collections.ts(2410,17): error TS2012: Cannot convert '{}' to 'BSTreeNode<T>': Type '{}' is missing property 'element' from type 'BSTreeNode<T>'.
```

Making the following corrections seems to sort it out:

Line 1511 changed to "this.list = new LinkedList<T>();"
Line 2405 changed to "var queue = new Queue<BSTreeNode<T>>();"

Hope this comment helps others and that you get these or other corrections done in the code so it compiles. Let me know if I can be of any assistance.

**Comment by Valve** [comment]
I PRd to fix this and similar issues. 
https://github.com/Valve/typescript-collections/commit/07d171159a77ab6918432b61bc5c2698029fbbf3

**Comment by basarat** [comment]
> I PRd to fix this and similar issues. 

Thanks :)

**Comment by drminor** [comment]
I changed 
Line 1511 to         this.list = new LinkedList<T>();

Line 2411 to       node = <BSTreeNode<T>> queue.dequeue();
