### ISSUE TITLE
Using libary with Aurelia/Typescript

### ISSUE THREAD

**Issue by zedL** [basarat/typescript-collections#54]
Hello, 
I cant get this lib to fly with aurelia.
I registered the lib:

```
// aurelia.json
{
   "name": "typescript-collections",
   "path": "../node_modules/typescript-collections/dist",
   "main": "lib/umd.min"
}
```

And use an import :

```
// someServics.ts
import * as Collections from 'typescript-collections';
```

But I get an error: vendor-bundle.js:3763 Uncaught Error: Load timeout for modules: ....
Can anyone help please?

**Comment by cmichaelgraham** [comment]
@zedL - i think you need to specify the **_typescript-collections**_ dependency in the `aurelia.json` file like this:

``` javascript
          {
            "name": "typescript-collections",
            "path": "../node_modules/typescript-collections/dist/lib",
            "main": "index"
          }
```

here's a repo showing aurelia-cli based project working with typescript-collections:
https://github.com/cmichaelgraham/cli-typescript-collection-quickstart

ping @eisenbergeffect

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
