### ISSUE TITLE
Firefox error "SyntaxError: missing = in const declaration"

### ISSUE THREAD

**Issue by liquidboy** [basarat/typescript-collections#56]
When trying to use this library in Firefox I am getting the "SyntaxError: missing = in const declaration" 

it appears that Firefox < version 51 has a bug in its implementation of "for(const"  ....  

Below is the Mozilla bug tracking this : 
https://bugzilla.mozilla.org/show_bug.cgi?id=1101653

Just letting you all know that FF 52+ should resolve this ... 

p.s. the bug was being hit when the util.ts -> makeString method was being called .. That has a for loop using a const

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
