### ISSUE TITLE
building the library...

### ISSUE THREAD

**Issue by datumgeek** [basarat/typescript-collections#57]
this library is fantastic :smile:

i copied the structure for a project i'm working on.

i noticed that in the package.json, none of the commands run `tsd install`, but i had to do the following to get `npm run all` to work without errors:

``` bash
npm install -g tsd
tsd install
```

**Comment by episage** [comment]
That's right. It's the correct way as per in README.md

Closing this because of old age. If the issue persists, please let me know.
