### ISSUE TITLE
LinkedList remove all matching compare function

### ISSUE THREAD

**Issue by peku33** [basarat/typescript-collections#62]
Hi,

It would be nice to include method in LinkedList removing all elements matching compare function.

Something like:
```
export interface IMatchFunction<T> {
	(a: T): boolean
}

removeAll(removeMatch: IMatchFunction<T>): number {

	//Remove all elements for which removeMatch returned true
	
	//Returns number of removed elements
	
}
```

This would allow removing elements without having full object handles.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.

Please open a PR with this feature.
