### ISSUE TITLE
Reference equality by default

### ISSUE THREAD

**Issue by debdattabasu** [basarat/typescript-collections#66]
Hi. I added two separate functions to a set that were identical. 

set.add(() => {}) 
set.add(() => {})

Because of the way toString() works, the set ended up containing only one function which is not expected. For reference the es6 Set class behaves in an expected way. It only checks for reference equality on objects. 

This should be the default for Dictionary and Set in order to match es6 semantics. 

Regards.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
