### ISSUE TITLE
need @type  package  

### ISSUE THREAD

**Issue by vincedan** [basarat/typescript-collections#67]
do you have  a related @type package of collections,  the same thing as @types/bluebird-global does?  for this kind basic datatype should not be "import" anywhere..

**Comment by yohei1126** [comment]
It seems that this project does not have @types.
https://www.npmjs.com/search?q=@types/typescript-collections&page=1&ranking=optimal

They offer alternative solution.

```
Typings resolution

Remember to set "moduleResolution": "node", so TypeScript compiler can resolve typings in the node_modules/typescript-collections directory.
```

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
