### ISSUE TITLE
"Module not found" 

### ISSUE THREAD

**Issue by sadra-ab** [basarat/typescript-collections#69]
Hi there,
I am using VS17 Enterprise.
I can easily import "typescript-collections" if I set my "module" option to "commonjs" in my tsconfig.json.
However, as soon as I change it to "umd" or "amd", I get error (see the screenshot please) saying that "Cannot find module 'typescript-collections'", and, therefore, the two variables "queue" and "queue1" will be of type "any". I have also attached my tsconfig.json.

Any help will be greatly appreciated.

![main ts](https://cloud.githubusercontent.com/assets/1020642/23715375/0e249bee-03f2-11e7-8c95-60ace667e0d9.png)

![tsconfig json](https://cloud.githubusercontent.com/assets/1020642/23715265/a2d9d5b6-03f1-11e7-9ceb-da64b0140691.png)

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
