### ISSUE TITLE
Add .find() method

### ISSUE THREAD

**Issue by onury** [basarat/typescript-collections#70]
It'd be useful when you want to get a value not by it's key but any other attribute(s).
I currently extend the `Dictionary` class for this.
```ts
find(callback:(key:K, value:V) => any):V {
        let found:V;
        this.forEach((key:K, value:V) => {
            if (callback(key, value)) {
                found = value;
                return false; // break out
            }
            return undefined; // suppress "not all code paths return a value" error
        });
        return found;
 }
```
Note: `.get()` and `.set()` aliases (for `.getValue` and `.setValue()`) would be great too 🤔 

Great work btw!

**Comment by Talha-T** [comment]
This throws error `Variable 'found' is used before being assigned.` To suppress this, we have to set a default value for V, which is not possible due to it's type being unknown.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please let me know.
