### ISSUE TITLE
Allow LinkedDictionary setValue inserting to head

### ISSUE THREAD

**Issue by fedorl** [basarat/typescript-collections#71]
Currently setting value is adding to the list tail. Adding to the head is a frequent and useful operation (and if one needs it, there it is not possible to reuse anything in this implementation). 

In general I think it was better not to hide completely the linked list structure from outside and allow in the linked dictionary an optional custom linked list appender.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
