### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [basarat/typescript-collections#74]
Error during installation:
> typescript-collection@1.0.4 postinstall C:\Users\kshar\Documents\OneDrive\Scripts\Typescript\node_modules\typescript-collection
```
> typings install

'typings' is not recognized as an internal or external command,
operable program or batch file.
npm WARN jira-scripts@0.0.1 No repository field.
npm WARN jira-scripts@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-collection@1.0.4 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-collection@1.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kshar\AppData\Roaming\npm-cache\_logs\2017-07-24T12_33_12_280Z-debug.log
```
Typings is deprecated and type definitions are now installed with `npm i @types/abc`. Perhaps an update is needed to post install script?

**Comment by episage** [comment]
Fixed.

**Comment by pedy711** [comment]
I still face the same issue

**Comment by episage** [comment]
@pedy711 You need to provide more information or fill a Pull Request by yourself.
Thanks

**Comment by pedy711** [comment]
> npm install typescript-collection --save

> typescript-collection@1.0.4 postinstall Y:\Inventory\InventoryWebAngularUI\web-ui-with-routing\node_modules\typescript-collection
> typings install

'typings' is not recognized as an internal or external command,
operable program or batch file.
npm WARN @angular/animations@7.2.12 requires a peer of @angular/core@7.2.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.2.8 requires a peer of @angular/compiler@7.2.8 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-collection@1.0.4 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-collection@1.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by episage** [comment]
@pedy711 Please install the latest stable. You are using 1.0.4 while the latest is 1.3.2.

**Comment by pedy711** [comment]
npm i typescript-collection@1.3.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript-collection@1.3.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by pedy711** [comment]
when I run `npm i typescript-collection` shouldn't it automatically fetch the latest release?

**Comment by pedy711** [comment]
Oh my bad. The library is called `typescript-collections` (plural). I misunderstood it with another library called `typescript-collection` (singular) which is exactly at 1.0.4

Thanks anyway for prompt replies.
