### ISSUE TITLE
1.2.4 breaks import

### ISSUE THREAD

**Issue by bspeice** [basarat/typescript-collections#76]
I'm unable to import typescript-collections as of version 1.2.4. Right now I'm manually locking the version to 1.2.3. Let me know what I can do to help debug.

**Comment by episage** [comment]
Ok, I will look at that in 3 hours. Can you the code that doesn't work?

**Comment by marcinbelczewski** [comment]
I'm also experiencing the problem. 
With **Webpack** a problem occurs on bundling and with **tsc** compilation goes fine and errors pops up in runtime. 
I've put small example here: https://github.com/marcinbelczewski/tscolsproblem.git

**Comment by episage** [comment]
Thank's @marcinbelczewski , that helped me to solve it quicker.
For some weird reason `npm run all` did not generate umd.js during 1.2.4 publish to npm. 

1.2.5 fixes that and also adds `browser` field to `package.json` so Webpack can consume it when targeting a browser.
