### ISSUE TITLE
Identity Map?

### ISSUE THREAD

**Issue by chriseppstein** [basarat/typescript-collections#77]
I recently built an Identity Map data structure on top of the `Dictionary` data structure. It's like the `Set` in that keeps a single instance of an object for a given key, but it optimizes the use case of always using that single instance within other data structures so that mutations to it are always in sync, other javascript data structures like the default ES6 `Set` and `Map` objects also work much better when you can guarantee a single instance is in use. Also, this can cut down on memory usage by enabling GC on duplicative values.

https://gist.github.com/chriseppstein/11ae09e2d96f72af036645a481d879e3

Is there any interest in adding this here? If so, would love to get some feedback on the design before submitting a PR.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, please open a Pull Request.

**Comment by Pranit-Harekar** [comment]
@chriseppstein Is this been added?
