### ISSUE TITLE
Add support for a toKey symbol?

### ISSUE THREAD

**Issue by chriseppstein** [basarat/typescript-collections#78]
In ES6, the canonical use case for symbols is so that objects can implement special methods for use by other data structures. It seems like an ideal situation for this library to add support for a toKey method that could be used throughout this library. I implemented the concept in this data structure for identity map, but I think it could be generalized.

Unfortunately, there's not currently a way to create a typescript interface around a custom symbol. I suspect TS will add this soon enough, they've indicated they want to handle it on the issue tracker.

https://gist.github.com/chriseppstein/11ae09e2d96f72af036645a481d879e3

**Comment by episage** [comment]
I this this is a good change but I'm not up-to-date with current TypeScript features. Can you tell if this can break support in older browsers/nodejs?

**Comment by chriseppstein** [comment]
We can feature detect whether `Symbol()` is supported. In those versions, users would have to provide a string function.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
