### ISSUE TITLE
Support the Iterator protocol

### ISSUE THREAD

**Issue by chriseppstein** [basarat/typescript-collections#80]
I noticed most of these data structures don't support the ES6 iterator protocol: 
`*[Symbol.iterator](): IterableIterator<T>`. Is the any interest in adding support for this protocol throughout the library so that these data structures can be used with `for..of` loops?

I implemented this for the identity map data structure (See issue #77) and it has been very useful.

**Comment by episage** [comment]
I think this is a good change again provided that it won't break compatibility. Can you issue a PR together with tests?

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
