### ISSUE TITLE
"strict" compiler setting

### ISSUE THREAD

**Issue by hmil** [basarat/typescript-collections#83]
Hi, is there any reason why the library is not compiled with the "strict" option enabled? 
I noticed inconsistencies in the api mostly due to the fact the library is not compiled with "strictNullChecks". Would you consider making the code `strict` compliant? I can provide a PR if your are interested.

**Comment by hmil** [comment]
I just created a PR which makes the whole codebase compliant with `--strict`.
Please give it some thought; Despite its great quality this library is useless to me if it does not adhere to the strict compilation setting.

**Comment by episage** [comment]
Thank you. I merged your changes in #85
