### ISSUE TITLE
Isn't there a way to get item from Set without forEach() ?

### ISSUE THREAD

**Issue by Talha-T** [basarat/typescript-collections#87]

**Comment by Jimeh87** [comment]
You can check if an item exists in a set, and you can iterate over the items in a set. How else would you expect to get an item from a set?

**Comment by alexandrucancescu** [comment]
You probably want to use a list. A set is a collections of unique objects where the order of the items does not matter

**Comment by Talha-T** [comment]
Oh,  thanks.  I didn't notice LinkedList before.
