### ISSUE TITLE
Compile error in latest version.

### ISSUE THREAD

**Issue by gregoryagu** [basarat/typescript-collections#9]
I just downloaded the latest Typescript, and tried the collection library, but there are some compile errors in collection.ts.

Cannot convert 'LinkedList<{}>' to 'LinkedList<T>':

constructor() {
            this.list = new LinkedList();
        }

I think there may have been some changes in the latest TS that broke some lines.

In any case, I think the library is great - good work!

Greg

**Comment by basarat** [comment]
@gregoryagu thanks! 

Can you check your compiler version since it compiles fine for me :
![image](https://f.cloud.github.com/assets/874898/2239184/6cc2167c-9c1c-11e3-80cd-9bd529524fae.png)

**Comment by gregoryagu** [comment]
Well, I downloaded the latest collection.ts and compiled, and this time it worked fine.  I am not sure what happened last time.

By the way, I have seen you on SO.  Thanks for answering questions there - I am still learning a lot about Typescript, and think it has a lot of potential.   

Do you think MS will ever do a "Base Class Library" with Typescript like they did with .net?  I find myself lost in trying to find the usual classes (like collections) that I am so familiar with in C#. Have you found a good source for such classes?  Your collections class is the best I have found for collections, but there are so many classes in .net that I certainly don't want to write to get an app going in Typescript.

**Comment by basarat** [comment]
> Thanks for answering questions there

Thank you :)

> Do you think MS will ever do a "Base Class Library" with Typescript

Ever is a long time, in that time frame its inevitable. But I don't think its going to happen soon. The TypeScript compiler itself depends on a number of data structures, all are a part of the compiler and not using a third party lib.
