### ISSUE TITLE
May I write an article comparing features with your library?

### ISSUE THREAD

**Issue by samchon** [basarat/typescript-collections#94]
Nice to meet you. I'm a developer of [**TSTL**](https://github.com/samchon/tstl), migration project of C++ STL (Standard Template Library) to TypeScript. Traveling similar libraries with me, finally I found this repository.

TSTL provides 4 modules (containers, iterators, algorithms and functors) and in the container module, many features are seemed like similar with you. To announce my library to the world, I',m planning to write an article comparing my library (TSTL) with others. The article will concentrate on which features are supported and which are not. The comparison would be represented by table.

  - The table will be seemed like this: https://gist.github.com/samchon/e3009c9a5685e295dfff24b48b80d2c5

Before writing the article, I think I should get permission from the origin developer of the compared libraries. May I write the article including your library? If you don't want, then I will not include yours.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
