### ISSUE TITLE
Complexities of the methods

### ISSUE THREAD

**Issue by caph1993** [basarat/typescript-collections#99]
Could you add the complexity of each method in the documentation or as a brief summary in the readme?

The main reason many people will opt for using this library is because it is **correct** and **fast**. The correctness part is clear from your motto _"It is a complete, fully **tested** data structure library written in TypeScript."_, but the speed warranty is not explicitly shown.

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
